services:
  slurmjupyter:
    image: slurm-jupyter:2022.05.26.3
    build:
      context: ./context
      target: jupyter
    depends_on:
      - slurmmaster
    hostname: slurmjupyter
    user: admin
    volumes:
      - shared-vol:/home/admin
      - munge-key:/etc/munge:ro
    ports:
      - 8888:8888
    deploy:
      mode: global

  slurmmaster:
    image: slurm-master:2022.05.26.3
    build:
      context: ./context
      target: master
    hostname: slurmmaster
    user: admin
    volumes:
      - shared-vol:/home/admin
      - munge-key:/etc/munge
    ports:
      - 6817:6817
      - 6818:6818
      - 6819:6819
    deploy:
      mode: global

  slurmnode:
    image: slurm-node:2022.05.26.3
    build:
      context: ./context
      target: node
    depends_on:
      - slurmmaster
    user: admin
    volumes:
      - shared-vol:/home/admin
      - munge-key:/etc/munge:ro
    links:
      - slurmmaster
    deploy:
      mode: replicated
      replicas: 3

volumes:
  shared-vol:
  munge-key:
