services:
  slurmjupyter:
    image: slurm-jupyter:2022.05.25.1
    build:
      context: ./context
      dockerfile: ../jupyter/Dockerfile
    hostname: slurmjupyter
    user: admin
    volumes:
      - shared-vol:/home/admin
    ports:
      - 8888:8888
    deploy:
      mode: global

  slurmmaster:
    image: slurm-master:2022.05.25.1
    build:
      context: ./context
      dockerfile: ../master/Dockerfile
    hostname: slurmmaster
    user: admin
    volumes:
      - shared-vol:/home/admin
    ports:
      - 6817:6817
      - 6818:6818
      - 6819:6819
    deploy:
      mode: global

  slurmnode:
    image: slurm-node:2022.05.25.1
    build:
      context: ./context
      dockerfile: ../node/Dockerfile
    user: admin
    volumes:
      - shared-vol:/home/admin
    links:
      - slurmmaster
    deploy:
      mode: replicated
      replicas: 3

volumes:
  shared-vol:
